templateRepository:
  gitProvider: shilpa_test
  path: "jfrog/jfrog-pipelines"
  branch: master
  templateFolder: templates/artifactory/cleanup/artifact-cleanup

publishTemplate:
  namespace: myCompany
  name: artifactCleanup
  version: 1.0.0
  pipelineName: publish_artifact_cleanup_template
  artifactoryIntegration: shilpa_art
  jfrogAccessTokenIntegration: shilpa_token
