resources:
  - name: Maven_App
    type: GitRepo
    configuration:
      path: jfrog/jfrog-pipelines
      gitProvider: GitHubIntegration
      branches:
        include: main

  - name: Maven_App_PR1
    type: GitRepo
    configuration:
      path: jfrog/jfrog-pipelines
      gitProvider: GitHubIntegration     
      buildOn:
        commit: false
        pullRequestCreate: true

  - name: Maven_App_Sonar_Report
    type: CodeAnalysis
    configuration:
      integration: SonarIntegration

pipelines:
  - name: SonarIntegration_Pipeline
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: scan
        type: Bash
        configuration:
          inputResources:
            - name: Maven_App           
          outputResources:
            - name: Maven_App_Sonar_Report
          integrations:
            - name: myArtifactory
          runtime:
            type: image
            image:
              custom:
                registry: myArtifactory
                sourceRepository: example-docker-local
                name: pipelines.jfrog.io/example-docker-local/sonar-scanner
                tag: latest
        execution:
          onExecute:
            - task: jfrog/sonar@v1.0.0
              input:
                codeResourceName: Maven_App_Sonar_Report
                gitResourceName: Maven_App
                projectFolder: simple-java-maven-app
                gitBranch: main
                orgName: jfrogsonarcodeanalysis
                projectKey: jfrogsonarcodeanalysis_mavenapp


      - name: scan_pr
        type: Bash
        configuration:
          inputResources:
            - name: Maven_App_PR1
          outputResources:
            - name: Maven_App_Sonar_Report
          integrations:
            - name: myArtifactory
          runtime:
            type: image
            image:
              custom:
                registry: myArtifactory
                sourceRepository: example-docker-local
                name: pipelines.jfrog.io/example-docker-local/sonar-scanner
                tag: latest
        execution:
          onExecute:
            - task: jfrog/sonar@v1.0.0
              input:
                codeResourceName: Maven_App_Sonar_Report
                gitResourceName: Maven_App_PR1
                gitBranch: main
                orgName: jfrogsonarcodeanalysis
                projectKey: jfrogsonarcodeanalysis_mavenapp
                extraSonarOptions: "-Dsonar.pullrequest.key=$res_demo_app_git_pr1_pullRequestNumber -Dsonar.pullrequest.branch=$res_demo_app_git_pr1_headCommitRef -Dsonar.pullrequest.base=$res_demo_app_git_pr1_pullRequestBaseBranch"
