resources:
  - name: demo_app_git
    type: GitRepo
    configuration:
      path: jfrog/jfrog-pipelines
      gitProvider: GitHubIntegration
      branches:
        include: main

  - name: demo_app_git_pr1
    type: GitRepo
    configuration:
      path: jfrog/jfrog-pipelines
      gitProvider: GitHubIntegration     
      buildOn:
        commit: false
        pullRequestCreate: true

  - name: demo_app_sonar_report
    type: CodeAnalysis
    configuration:
      integration: SonarIntegration

pipelines:
  - name: sonar_demo_pipeline
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: scan
        type: Bash
        configuration:
          inputResources:
            - name: demo_app_git            
          outputResources:
            - name: demo_app_sonar_report
          integrations:
            - name: JFrogPlatformIntegration
          runtime:
            type: image
            image:
              custom:
                registry: JFrogPlatformIntegration
                sourceRepository: example-docker-local
                name: pipelines.jfrog.io/artifactory/example-docker-local/sonar-scanner
                tag: latest
        execution:
          onExecute:
            - task: jfrog/sonar@v1.0.0
              input:
                codeResourceName: demo_app_sonar_report
                gitResourceName: demo_app_git
                gitBranch: main
                orgName: jfrogsonarcodeanalysis
                projectKey: jfrogsonarcodeanalysis_mavenapp


      - name: scan_pr
        type: Bash
        configuration:
          inputResources:
            - name: demo_app_git_pr1
          outputResources:
            - name: demo_app_sonar_report
          integrations:
            - name: JFrogPlatformIntegration
          runtime:
            type: image
            image:
              custom:
                registry: JFrogPlatformIntegration
                sourceRepository: example-docker-local
                name: pipelines.jfrog.io/artifactory/example-docker-local/sonar-scanner
                tag: latest
        execution:
          onExecute:
            - task: jfrog/sonar@v1.0.0
              input:
                codeResourceName: demo_app_sonar_report
                gitResourceName: demo_app_git_pr1
                gitBranch: master
                orgName: kunal-mazumdar
                projectKey: kunal-mazumdar_demo
                extraSonarOptions: "-Dsonar.pullrequest.key=$res_demo_app_git_pr1_pullRequestNumber -Dsonar.pullrequest.branch=$res_demo_app_git_pr1_headCommitRef -Dsonar.pullrequest.base=$res_demo_app_git_pr1_pullRequestBaseBranch"
