resources:
  - name: Code_Analysis
    type: GitRepo
    configuration:
      path: jfrog/jfrog-pipelines/simple-java-maven-app
      gitProvider: GitHubIntegration
      branches:
        include: main

  - name: MavenApp
    type: GitRepo
    configuration:
      path: jfrog/jfrog-pipelines/simple-java-maven-app
      gitProvider: GitHubIntegration      
      buildOn:
        commit: false
        pullRequestCreate: true

  - name: SonarReport
    type: CodeAnalysis
    configuration:
      integration: SonarIntegration

pipelines:
  - name: SonarIntegration
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: ScanCode
        type: Bash
        configuration:
          inputResources:
            - name: Code_Analysis
          outputResources:
            - name: SonarReport
          integrations: 
            - name: JFrogPlatformIntegration # artifactory integration to pull task from artifact
          runtime:
            type: image
            image:
              custom:
                registry: artifactory
                sourceRepository: example-docker-local
                name: pipelines.jfrog.io/example-docker-local/sonar-scanner
                tag: latest
          
        execution:            
          onExecute:
            - task: jfrog/sonar@v1.0.0
              id: code_analysis_version
              input:
                codeResourceName: SonarReport
                gitResourceName: MavenApp
                gitBranch: main #source code branch
                orgName: jfrogsonarcodeanalysis  # sonar org name
                projectKey: jfrogsonarcodeanalysis_mavenapp # sonar org_project name
                extraSonarOptions: "-Dsonar.pullrequest.key=$res_demo_app_git_pr1_pullRequestNumber -Dsonar.pullrequest.branch=$res_demo_app_git_pr1_headCommitRef -Dsonar.pullrequest.base=$res_demo_app_git_pr1_pullRequestBaseBranch"                
