resources:
  - name: maven_app
    type: GitRepo
    configuration:
      path: jfrog/jfrog-pipelines
      gitProvider: GitHubIntegration
      branches:
        include: main
        
  - name: maven_app_sonar_report
    type: CodeAnalysis
    configuration:
      integration: SonarIntegration

pipelines:
  - name: sonar_integration_pipeline
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: scan
        type: Bash
        configuration:
          inputResources:
            - name: maven_app           
          outputResources:
            - name: maven_app_sonar_report
          integrations:
            - name: myArtifactory
          runtime:
            type: image
            image:
              custom:
                registry: myArtifactory
                sourceRepository: example-docker-local
                name: pipelines.jfrog.io/example-docker-local/sonar-scanner
                tag: latest
        execution:
          onExecute:
            - task: jfrog/sonar@v1.0.0
              input:
                codeResourceName: maven_app_sonar_report
                gitResourceName: maven_app
                projectFolder: simple-java-maven-app
                gitBranch: main
                orgName: jfrogsonarcodeanalysis
                projectKey: jfrogsonarcodeanalysis_mavenapp
